/*
 * Collaborators:
 * Avinash Joshi <axj107420@utdallas.edu>
 * Sandeep Shenoy <sxs115220@utdallas.edu>
 * Shishir Krishnaprasad <sxk116430@utdallas.edu>
 * 
 * (c) 2012 GODSe
 */
package com.utd.itc.godse.view;

import com.utd.itc.godse.action.CreateAction;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class CreateForm extends javax.swing.JFrame {

    /**
     * Creates new form CreateForm
     */
    public CreateForm() {
        initComponents();
        myInitComponents();
    }

    public void myInitComponents() {
        create.addActionListener(new CreateAction(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileNameLbl = new javax.swing.JLabel();
        ApplicationName = new javax.swing.JLabel();
        fileName = new javax.swing.JTextField();
        docDataScrollPane = new javax.swing.JScrollPane();
        docData = new javax.swing.JTextArea();
        KeyLbl = new javax.swing.JLabel();
        key = new javax.swing.JTextField();
        ConfirmKeyLbl = new javax.swing.JLabel();
        confirmKey = new javax.swing.JTextField();
        close = new javax.swing.JButton();
        create = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(100, 75));
        setPreferredSize(new java.awt.Dimension(800, 540));
        setSize(new java.awt.Dimension(800, 540));

        FileNameLbl.setText("File Name");

        ApplicationName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ApplicationName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ApplicationName.setText("Google Docs Secured (GoDSe)");
        ApplicationName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        docData.setColumns(20);
        docData.setRows(300);
        docDataScrollPane.setViewportView(docData);

        KeyLbl.setText("Key");

        key.setToolTipText("Key");
        key.setName("key");

        ConfirmKeyLbl.setText("Confirm Key");

        confirmKey.setToolTipText("Confirm Key");
        confirmKey.setName("confirmKey");

        close.setText("Close");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        create.setText("Create");

        errorMsg.setForeground(new java.awt.Color(255, 51, 51));
        errorMsg.setToolTipText("Error Message");
        errorMsg.setName("errorMsg");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(docDataScrollPane))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(FileNameLbl)
                                .add(18, 18, 18)
                                .add(fileName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 202, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(250, 250, 250)
                                .add(ApplicationName)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(124, 124, 124)
                .add(KeyLbl)
                .add(18, 18, 18)
                .add(key, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(43, 43, 43)
                .add(ConfirmKeyLbl)
                .add(29, 29, 29)
                .add(confirmKey, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(errorMsg, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(close, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(create, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(ApplicationName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(FileNameLbl)
                    .add(fileName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(docDataScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 336, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(KeyLbl)
                    .add(key, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ConfirmKeyLbl)
                    .add(confirmKey, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(close)
                    .add(create)
                    .add(errorMsg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        key.getAccessibleContext().setAccessibleName("key");
        confirmKey.getAccessibleContext().setAccessibleName("confirmKey");
        errorMsg.getAccessibleContext().setAccessibleName("errorMsg");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    public int validateForm() {
        if ("".equalsIgnoreCase(fileName.getText())) {
            return -3;
        }
        if ("".equalsIgnoreCase(docData.getText())) {
            return -4;
        }
        if ("".equalsIgnoreCase(key.getText()) || "".equalsIgnoreCase(confirmKey.getText())) {
            return -2;
        }
        if (!key.getText().equals(confirmKey.getText())) {
            return -1;
        }

        return 1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CreateForm().setVisible(true);
            }
        });
    }

    public void showErrorMessage(String message) {

        errorMsg.setVisible(true);
        errorMsg.setText("");
        errorMsg.setText("* " + message);
    }

    public void hideErrorMessage() {
        errorMsg.setVisible(false);
    }

    public JTextField getConfirmKey() {
        return confirmKey;
    }

    public void setConfirmKey(JTextField confirmKey) {
        this.confirmKey = confirmKey;
    }

    public JTextArea getDocData() {
        return docData;
    }

    public void setDocData(JTextArea docData) {
        this.docData = docData;
    }

    public JTextField getFileName() {
        return fileName;
    }

    public void setFileName(JTextField fileName) {
        this.fileName = fileName;
    }

    public JTextField getKey() {
        return key;
    }

    public void setKey(JTextField key) {
        this.key = key;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApplicationName;
    private javax.swing.JLabel ConfirmKeyLbl;
    private javax.swing.JLabel FileNameLbl;
    private javax.swing.JLabel KeyLbl;
    private javax.swing.JButton close;
    private javax.swing.JTextField confirmKey;
    private javax.swing.JButton create;
    private javax.swing.JTextArea docData;
    private javax.swing.JScrollPane docDataScrollPane;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JTextField fileName;
    private javax.swing.JTextField key;
    // End of variables declaration//GEN-END:variables
}
