/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utd.itc.godse.view;

import com.utd.itc.godse.action.LoginAction;
import java.awt.Event;

/**
 *
 * @author GoDSe
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        myInitComponents();
    }

    public void myInitComponents() {
        login.addActionListener(new LoginAction(this));
        hideAuthMsg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserNameLbl = new javax.swing.JLabel();
        PasswordLbl = new javax.swing.JLabel();
        ApplicationName = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        errorMsg = new javax.swing.JLabel();
        authMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GoDSe");
        setLocation(new java.awt.Point(22, 22));
        setLocationByPlatform(true);
        setName("loginFrame");

        UserNameLbl.setText("UserName");

        PasswordLbl.setText("Password");

        ApplicationName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ApplicationName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ApplicationName.setText("Google Docs Secured (GoDSe)");

        userName.setToolTipText("Enter your username");
        userName.setName("userName");

        login.setText("Login");
        login.setToolTipText("Login");
        login.setName("login");

        reset.setText("Reset");
        reset.setToolTipText("reset");
        reset.setName("reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });

        password.setToolTipText("Enter your password");
        password.setName("password");
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        errorMsg.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(255, 0, 51));
        errorMsg.setText("*");
        errorMsg.setVisible(false);

        authMsg.setText("Authenticating...");
        authMsg.setToolTipText("Authenticating with Google Server");
        authMsg.setName("authMsg");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(188, 188, 188)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(password)
                            .add(userName)))
                    .add(layout.createSequentialGroup()
                        .add(0, 315, Short.MAX_VALUE)
                        .add(reset)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(login)))
                .add(76, 76, 76))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(162, 162, 162)
                        .add(ApplicationName))
                    .add(layout.createSequentialGroup()
                        .add(38, 38, 38)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(authMsg)
                            .add(errorMsg)
                            .add(UserNameLbl)
                            .add(PasswordLbl))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(ApplicationName)
                .add(37, 37, 37)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(UserNameLbl)
                    .add(userName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(41, 41, 41)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(PasswordLbl)
                    .add(password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(41, 41, 41)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(login)
                    .add(reset))
                .add(18, 18, 18)
                .add(errorMsg)
                .add(18, 18, 18)
                .add(authMsg)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        userName.getAccessibleContext().setAccessibleName("userName");
        userName.getAccessibleContext().setAccessibleDescription("userName");
        login.getAccessibleContext().setAccessibleName("login");
        reset.getAccessibleContext().setAccessibleName("reset");
        password.getAccessibleContext().setAccessibleName("password");

        getAccessibleContext().setAccessibleDescription("LoginFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        userName.setText("");
        password.setText("");
        errorMsg.setVisible(false);
        hideAuthMsg();
    }//GEN-LAST:event_resetMouseClicked

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        //System.out.println("KeyCode: " + evt.getKeyCode());
        if(evt.getKeyCode() == 10)
        {
            errorMsg.setVisible(false);
            showAuthMsg();
            this.login.doClick();
            
        }
    }//GEN-LAST:event_passwordKeyPressed

    public boolean validateInput() {
        errorMsg.setVisible(false);
        if ("".equalsIgnoreCase(userName.getText().trim()) || "".equalsIgnoreCase(new String(password.getPassword()).trim())) {
            return false;
        } 
        return true;
    }

    public String getUserName() {
        return userName.getText().trim();
    }

    public String getPassword() {
        return new String(password.getPassword()).trim();
    }

    public void showErrorMessage(String message) {
        hideAuthMsg();
        errorMsg.setVisible(true);
        errorMsg.setText("");
        errorMsg.setText("* "+ message);
    }
    
    public void hideAuthMsg()
    {
        authMsg.setVisible(false);
    }

    public void showAuthMsg()
    {
        authMsg.setVisible(true);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApplicationName;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JLabel UserNameLbl;
    private javax.swing.JLabel authMsg;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
